with open("meus_livros.csv","w") as f:
    f.write("Título,Autor,Ano de publicação,Número de páginas\n")
    f.write("Jantar Secreto,Raphael Montes,2016,368\n")
    f.write("Quinze Dias,Vitor Martins,2022,288\n")
    f.write("Os Sete Maridos de Evelyn Hugo,Taylor Jenkins Reid,2019,360\n")
    f.write("Os Dois Morrem no Final,Adam Silveira,2021,416\n")
    f.write("Mentirosos,E. Lockart,2014,272\n")
    f.write("As Vantagens de Ser Invisível,Stephen Chbosky,2007,224\n")
    f.write("Jogos de Herança,Jennifer Lynn Barnes,2021,432\n")
    f.write("Não Foi Por Acaso,Vinicius Grossos,2021,192\n")
    f.write("A Paciente Silenciosa,Alex Michaelides,2019,364\n")
    f.write("Minha Versão de Você,Christina Lauren,2020,226\n")